CREATE TABLE QQW84224.EMPLOYEE (
	SK_EMPLOYEE INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(25) NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    POSITION VARCHAR(100),
    RATE_PER_HOUR DECIMAL(12,2),
    SK_COMPANY INT NOT NULL,
    SK_SHIFT INT NOT NULL,
    AUDIT_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (SK_COMPANY) REFERENCES COMPANY(SK_COMPANY),
    FOREIGN KEY (SK_SHIFT) REFERENCES SHIFT(SK_SHIFT)
);

INSERT INTO QQW84224.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, POSITION, RATE_PER_HOUR, SK_COMPANY ,SK_SHIFT) 
	VALUES ('cabalpa', 'Paul', 'Caballero','Management','Superuser',56.5,1,1);
INSERT INTO QQW84224.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, POSITION, RATE_PER_HOUR, SK_COMPANY ,SK_SHIFT) 
	VALUES ('cabalhail', 'Hailey', 'Caballero','Management','User',50.5,1,1);

INSERT INTO QQW84224.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, POSITION, RATE_PER_HOUR, SK_COMPANY ,SK_SHIFT) 
	VALUES ('reyesw', 'Willie', 'Reyes','Management','User',0.0,1,1);

INSERT INTO QQW84224.EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, POSITION, RATE_PER_HOUR, SK_COMPANY ,SK_SHIFT) 
	VALUES ('bangijr', 'Ray John', 'Bangi','Management','User',0.0,1,1);

CREATE TABLE QQW84224.SHIFT (
    SK_SHIFT INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SHIFT_CODE VARCHAR(25) NOT NULL,
    SHIFT_TIMEIN TIME,
    SHIFT_TIMEOUT TIME,
    AUDIT_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);
INSERT INTO QQW84224.SHIFT (SHIFT_CODE, SHIFT_TIMEIN, SHIFT_TIMEOUT) VALUES ('AM01', '08:00:00','17:00:00');
INSERT INTO QQW84224.SHIFT (SHIFT_CODE, SHIFT_TIMEIN, SHIFT_TIMEOUT) VALUES ('AM02', '09:00:00','18:00:00');

CREATE TABLE QQW84224.COMPANY (
    SK_COMPANY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COMPANY_ID VARCHAR(25) NOT NULL,
    COMPANY_NAME VARCHAR(250),
    AUDIT_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);
INSERT INTO QQW84224.COMPANY (COMPANY_ID, COMPANY_NAME) VALUES ('EBLO', 'ELEAZAR BANGI LAW OFFICE');

CREATE TABLE QQW84224.USERACCOUNT (
    SK_USER INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SK_EMPLOYEE INT NOT NULL,
    USERNAME VARCHAR(25),
    PASSWORD VARCHAR(25),
    AUDIT_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (SK_EMPLOYEE) REFERENCES EMPLOYEE(SK_EMPLOYEE)
);
INSERT INTO QQW84224.UserAccount (SK_EMPLOYEE, USERNAME, PASSWORD) VALUES (1,'admin','admin');
INSERT INTO QQW84224.UserAccount (SK_EMPLOYEE, USERNAME, PASSWORD) VALUES (2,'hailey','hailey');
INSERT INTO QQW84224.UserAccount (SK_EMPLOYEE, USERNAME, PASSWORD) VALUES (3,'reyesw','reyesw');
INSERT INTO QQW84224.UserAccount (SK_EMPLOYEE, USERNAME, PASSWORD) VALUES (4,'bangijr','bangijr');

CREATE TABLE TIMEENTRIES (
    SK_TIME_ENTRY INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SK_EMPLOYEE INT NOT NULL,
    CLOCKIN_DATETIME DATETIME,
    CLOCKOUT_DATETIME DATETIME,
    TOTAL_HRS TIME,
    AUDIT_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (SK_EMPLOYEE) REFERENCES EMPLOYEE(SK_EMPLOYEE)
);
INSERT INTO QQW84224.TimeEntries (SK_EMPLOYEE, CLOCKIN_DATETIME, CLOCKOUT_DATETIME, TOTAL_HRS) VALUES (1, '2024-01-13-07.30.30.000000', '2024-01-13-18.00.00.000000',NULL);
INSERT INTO TIMEENTRIES (SK_EMPLOYEE, CLOCKIN_DATETIME)VALUES (1, (CURRENT TIMESTAMP - CURRENT TIMEZONE) + 8 HOURS)

ALTER TABLE TIMEENTRIES
ADD NEW_TOTAL_HRS TIME;



CREATE TABLE QQW84224.CHANGE_LOG (
    SK_CHANGE INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SK_USER INT NOT NULL,
    DESCRIPTION VARCHAR(250),
    AUDIT_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (SK_USER) REFERENCES USERACCOUNT(SK_USER)
);

