CREATE TABLE QQW84224.Employees (
    EMPLOYEE_ID VARCHAR(25) PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DEPARTMENT VARCHAR(255),
    POSITION VARCHAR(255),
    RATE_PER_HOUR DECIMAL(12,2),
    AUDIT_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

INSERT INTO QQW84224.Employees (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, POSITION, RATE_PER_HOUR) VALUES ('cabalpa', 'Admin', 'admin','Management','Superuser',56.5);

CREATE TABLE UserAccount (
    USER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(25) NOT NULL,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    AUDIT_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

INSERT INTO QQW84224.UserAccount (EMPLOYEE_ID, USERNAME, PASSWORD) VALUES ('cabalpa', 'admin','admin')

CREATE TABLE TimeEntries (
    ENTRY_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(25) NOT NULL,
    CLOCKIN_DATETIME DATETIME,
    CLOCKOUT_DATETIME DATETIME,
    TOTAL_HRS DECIMAL(10, 2),
    AUDIT_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);
INSERT INTO QQW84224.TimeEntries (EMPLOYEE_ID, CLOCKIN_DATETIME, CLOCKOUT_DATETIME, TOTAL_HRS) VALUES ('cabalpa', 'Admin', 'admin','Management','Superuser',56.5);
